[package]
name = "sol-client"
version = "0.1.0"
edition = "2021"
description = "SolGrid CLI: airdrop, mint setup, job creation, escrow funding."

[[bin]]
name = "sol-client"
path = "src/main.rs"

[dependencies]
sol-common = { path = "../sol-common" }
sol-onchain = { path = "../sol-onchain" }
solana-sdk = { workspace = true }
solana-client = { workspace = true }
spl-token = { workspace = true }
spl-associated-token-account = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
clap = { version = "4", features = ["derive"] }
anyhow = { workspace = true }
uuid = { workspace = true }
bs58 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenvy = { workspace = true }
shellexpand = "3"
